# Generated by Django 3.2.5 on 2021-08-01 19:55

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('input_name', models.FilePathField(max_length=200)),
                ('input_path', models.FilePathField(max_length=200, unique=True)),
                ('output_path', models.FilePathField(max_length=200, unique=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Warning'), (2, 'Ok'), (3, 'Pending'), (4, 'Client Error'), (5, 'Server Error')], default=3)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='files.program')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
